"""
RYVA - Operator HMI (m's part)
Covers tasks m-1 through m-6, plus hysteresis (state must persist
before switching, prevents flicker).
Run this file directly: python ryva_hmi.py

REAL MODE: pulls live CLS scores from wss_server.py over WebSocket
(same feed the supervisor dashboard uses), and plays real audio
alerts generated by generate_audio.py.

Requires: pip install websocket-client gTTS pygame
Requires: run `python generate_audio.py` once first to create audio/*.mp3
Requires: wss_server.py and main_loop.py already running before this.
"""

import sys
import time
import json
import queue
import threading

import websocket
import pygame

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QStackedWidget, QWidget,
    QVBoxLayout, QGridLayout, QLabel, QPushButton, QProgressBar, QLCDNumber
)
from PyQt6.QtCore import QTimer, Qt
from PyQt6.QtGui import QFont


# ---------------------------------------------------------------------------
# STEP m-1: basic 3-panel switching window (colours only)
# ---------------------------------------------------------------------------
COLORS = {
    "GREEN": "#1B2B1B",
    "AMBER": "#2B2000",
    "RED":   "#2B0000",
}

# Page indices inside the QStackedWidget. Calibration is page 0.
PAGE_CALIBRATION = 0
PAGE_GREEN = 1
PAGE_AMBER = 2
PAGE_RED = 3

# WebSocket feed config - must match the operator_id main_loop.py broadcasts as
WS_URL = "ws://localhost:8765/ws"
OPERATOR_ID = "R001"

# Hysteresis - how long a new state must persist before RYVA actually
# switches to it. Prevents flickering on borderline scores.
HYSTERESIS_UP = 10    # seconds a HIGHER state must persist before switching up
HYSTERESIS_DOWN = 15  # seconds a LOWER state must persist before switching down
                      # (set to 15 for demo timing - spec value is 60, mention verbally)

pygame.mixer.init()


# ---------------------------------------------------------------------------
# STEP m-3: build the real GREEN / AMBER / RED layouts (not just colours)
# ---------------------------------------------------------------------------
def make_green_page():
    page = QWidget()
    page.setStyleSheet(f"background-color: {COLORS['GREEN']};")
    layout = QGridLayout()
    page.setLayout(layout)

    readouts = ["RPM", "Load", "Temp", "Vib", "CLS", "Time"]
    fake_values = ["1840", "3.2 t", "31 C", "OK", "18", "09:41"]

    page.value_labels = {}
    for i, (name, val) in enumerate(zip(readouts, fake_values)):
        row, col = divmod(i, 3)
        label = QLabel(name)
        label.setStyleSheet("color: #9fdca0; font-size: 16px;")
        value = QLabel(val)
        value.setStyleSheet("color: white; font-size: 24px; font-weight: bold;")
        value.setAlignment(Qt.AlignmentFlag.AlignCenter)
        cell_layout = QVBoxLayout()
        cell_layout.addWidget(label, alignment=Qt.AlignmentFlag.AlignCenter)
        cell_layout.addWidget(value)
        wrapper = QWidget()
        wrapper.setLayout(cell_layout)
        layout.addWidget(wrapper, row, col)
        page.value_labels[name] = value

    return page


def make_amber_page():
    page = QWidget()
    page.setStyleSheet(f"background-color: {COLORS['AMBER']};")
    layout = QVBoxLayout()
    page.setLayout(layout)

    warning = QLabel("⚠ FATIGUE RISING — TAKE CARE")
    warning.setStyleSheet("color: #ffcc66; font-size: 32px; font-weight: bold;")
    warning.setAlignment(Qt.AlignmentFlag.AlignCenter)
    layout.addWidget(warning)

    readouts = ["CLS Score", "Blink rate", "Head tilt"]
    fake_values = ["55", "22/min", "18 deg"]
    page.value_labels = {}
    for name, val in zip(readouts, fake_values):
        value = QLabel(f"{name}: {val}")
        value.setStyleSheet("color: white; font-size: 22px;")
        value.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(value)
        page.value_labels[name] = value

    return page


def make_red_page():
    page = QWidget()
    page.setStyleSheet(f"background-color: {COLORS['RED']};")
    layout = QVBoxLayout()
    page.setLayout(layout)

    stop_label = QLabel("STOP")
    stop_label.setStyleSheet("color: white; font-size: 48px; font-weight: bold;")
    stop_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

    status_label = QLabel("HIGH FATIGUE DETECTED — HAND OVER / TAKE A BREAK")
    status_label.setStyleSheet("color: #ff9999; font-size: 20px;")
    status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
    status_label.setWordWrap(True)

    layout.addWidget(stop_label)
    layout.addWidget(status_label)
    page.status_label = status_label
    return page


# ---------------------------------------------------------------------------
# STEP m-6: calibration screen (shortened here for demo/testing - change
# CALIBRATION_SECONDS to 180 for the real 3-minute version)
# ---------------------------------------------------------------------------
CALIBRATION_SECONDS = 10  # set to 180 for the real thing - keep in sync with main_loop.py


def make_calibration_page():
    page = QWidget()
    page.setStyleSheet("background-color: #101010;")
    layout = QVBoxLayout()
    page.setLayout(layout)

    instructions = QLabel("Look at the camera and grip normally.\nCalibrating...")
    instructions.setStyleSheet("color: white; font-size: 20px;")
    instructions.setAlignment(Qt.AlignmentFlag.AlignCenter)

    lcd = QLCDNumber()
    lcd.setStyleSheet("color: #66ff66;")
    lcd.display(CALIBRATION_SECONDS)

    progress = QProgressBar()
    progress.setMaximum(CALIBRATION_SECONDS)
    progress.setValue(0)

    layout.addWidget(instructions)
    layout.addWidget(lcd)
    layout.addWidget(progress)

    page.lcd = lcd
    page.progress = progress
    return page


# ---------------------------------------------------------------------------
# Main window - wires everything together
# ---------------------------------------------------------------------------
class RyvaHMI(QMainWindow):
    def __init__(self, cls_queue):
        super().__init__()
        self.setWindowTitle("RYVA - Operator Display")
        self.resize(900, 500)

        self.cls_queue = cls_queue
        self.current_state = "CALIBRATING"
        self.amber_start_time = None
        self.rest_suggested = False
        self.last_below_threshold_time = None

        # Hysteresis tracking
        self.pending_state = None
        self.pending_since = None

        self.stack = QStackedWidget()
        self.setCentralWidget(self.stack)

        self.calibration_page = make_calibration_page()
        self.green_page = make_green_page()
        self.amber_page = make_amber_page()
        self.red_page = make_red_page()

        self.stack.addWidget(self.calibration_page)  # index 0
        self.stack.addWidget(self.green_page)          # index 1
        self.stack.addWidget(self.amber_page)          # index 2
        self.stack.addWidget(self.red_page)             # index 3

        self.stack.setCurrentIndex(PAGE_CALIBRATION)

        # calibration countdown timer
        self.calib_remaining = CALIBRATION_SECONDS
        self.calib_timer = QTimer()
        self.calib_timer.timeout.connect(self.tick_calibration)
        self.calib_timer.start(1000)

        # queue poll timer (this is the m-5 wiring step)
        self.poll_timer = QTimer()
        self.poll_timer.timeout.connect(self.poll_queue)
        self.poll_timer.start(100)

    # -----------------------------------------------------------------
    # STEP m-6: calibration countdown logic
    # -----------------------------------------------------------------
    def tick_calibration(self):
        self.calib_remaining -= 1
        self.calibration_page.lcd.display(self.calib_remaining)
        self.calibration_page.progress.setValue(
            CALIBRATION_SECONDS - self.calib_remaining
        )
        if self.calib_remaining <= 0:
            self.calib_timer.stop()
            self.current_state = "GREEN"
            self.stack.setCurrentIndex(PAGE_GREEN)
            print("Calibration done. Baseline recorded.")

    # -----------------------------------------------------------------
    # STEP m-5: poll the queue for the live CLS score and switch state
    # -----------------------------------------------------------------
    def poll_queue(self):
        if self.current_state == "CALIBRATING":
            return
        try:
            cls_score = self.cls_queue.get_nowait()
        except queue.Empty:
            return

        self.update_readout(cls_score)
        self.update_state(cls_score)

    # -----------------------------------------------------------------
    # Push the live CLS number into whichever page's readout is visible.
    # Runs every time a new score arrives, independent of state changes -
    # so the number updates continuously even while staying in one state.
    # -----------------------------------------------------------------
    def update_readout(self, cls_score):
        text = f"{cls_score:.0f}"
        if "CLS" in self.green_page.value_labels:
            self.green_page.value_labels["CLS"].setText(text)
        if "CLS Score" in self.amber_page.value_labels:
            self.amber_page.value_labels["CLS Score"].setText(f"CLS Score: {text}")

    # -----------------------------------------------------------------
    # Hysteresis: a state must persist for HYSTERESIS_UP (going up in
    # severity) or HYSTERESIS_DOWN (going down) seconds before RYVA
    # actually switches screens/audio. Prevents flicker on borderline
    # scores that hover right at a threshold.
    # -----------------------------------------------------------------
    def update_state(self, cls_score):
        if cls_score > 71:
            raw_state = "RED"
        elif cls_score > 41:
            raw_state = "AMBER"
        else:
            raw_state = "GREEN"

        severity = {"GREEN": 0, "AMBER": 1, "RED": 2}
        now = time.time()

        if raw_state == self.current_state:
            # Back within current state before any pending change matured
            self.pending_state = None
            self.pending_since = None
        else:
            if raw_state != self.pending_state:
                self.pending_state = raw_state
                self.pending_since = now

            going_up = severity[raw_state] > severity[self.current_state]
            required_hold = HYSTERESIS_UP if going_up else HYSTERESIS_DOWN

            if now - self.pending_since >= required_hold:
                new_state = raw_state
                print(f"State change: {self.current_state} -> {new_state} "
                      f"(CLS={cls_score}, held {required_hold}s)")
                self.current_state = new_state
                self.pending_state = None
                self.pending_since = None

                if new_state == "AMBER":
                    self.amber_start_time = time.time()
                    self.rest_suggested = False
                    self.stack.setCurrentIndex(PAGE_AMBER)
                    self.play_voice_alert("AMBER")
                elif new_state == "RED":
                    self.stack.setCurrentIndex(PAGE_RED)
                    self.play_voice_alert("RED")
                elif new_state == "GREEN":
                    self.amber_start_time = None
                    self.rest_suggested = False
                    self.stack.setCurrentIndex(PAGE_GREEN)

        # STEP m-7 (simplified): micro-rest check while in AMBER
        if self.current_state == "AMBER" and self.amber_start_time:
            amber_duration = time.time() - self.amber_start_time
            if amber_duration > 300 and not self.rest_suggested:
                self.rest_suggested = True
                self.play_voice_alert("REST")

    # -----------------------------------------------------------------
    # STEP m-4: voice alerts - REAL audio via pygame, generated by
    # generate_audio.py. Run that script once before starting this app.
    # -----------------------------------------------------------------
    def play_voice_alert(self, alert_type):
        path = f"audio/{alert_type.lower()}_en.mp3"
        try:
            pygame.mixer.Sound(path).play()
        except Exception as e:
            print(f"[VOICE ALERT] Failed to play {path}: {e}")


# ---------------------------------------------------------------------------
# REAL MODE: pull live CLS scores from wss_server.py over WebSocket.
# This is the same feed the supervisor dashboard connects to - we just
# filter for OPERATOR_ID's cls_update messages and push the score into
# the same queue.Queue() the UI code above already knows how to consume.
# ---------------------------------------------------------------------------
def real_cls_source(data_queue):
    def on_message(ws, message):
        try:
            msg = json.loads(message)
        except json.JSONDecodeError:
            return
        if msg.get("type") == "cls_update" and msg.get("operator_id") == OPERATOR_ID:
            print(f"[HMI] Received CLS={msg['cls']}")  # TEMP DEBUG - confirms data is arriving
            data_queue.put(msg["cls"])

    def on_error(ws, error):
        print(f"[HMI] WebSocket error: {error}")

    def on_close(ws, close_status_code, close_msg):
        print("[HMI] Disconnected from server, retrying in 3s...")
        time.sleep(3)
        run_ws()

    def on_open(ws):
        print(f"[HMI] Connected to {WS_URL}, listening for {OPERATOR_ID}...")

    def run_ws():
        ws = websocket.WebSocketApp(
            WS_URL,
            on_open=on_open,
            on_message=on_message,
            on_error=on_error,
            on_close=on_close,
        )
        ws.run_forever()

    threading.Thread(target=run_ws, daemon=True).start()


if __name__ == "__main__":
    cls_queue = queue.Queue()

    # --- REAL MODE: live data from wss_server.py ---
    # Make sure wss_server.py and main_loop.py are already running
    # before you start this script, or the HMI will just wait,
    # retrying the connection every 3 seconds.
    real_cls_source(cls_queue)

    app = QApplication(sys.argv)
    window = RyvaHMI(cls_queue)
    window.show()
    sys.exit(app.exec())